version: '3.7'
services:
    app:
        container_name: triproute
        volumes: 
            - ./:/app
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
   